const $ = (id) => document.getElementById(id);
const loginView = $("login-view"); const dashboard = $("dashboard");
async function request(action, options = {}) { const response = await fetch(`/api/admin?action=${action}`, { headers: { "Content-Type": "application/json" }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Request failed"); return data; }
function showDashboard() { window.location.assign("/admin/dashboard/"); }
async function loadMessages() { const state = $("message-state"); try { const { messages } = await request("messages"); state.textContent = messages.length ? `${messages.length} message${messages.length === 1 ? "" : "s"}` : "No support messages yet."; $("messages").innerHTML = messages.map((m) => `<article class="message"><div class="message-meta"><strong>${escapeHtml(m.name)}</strong><span>${escapeHtml(m.email)} · ${new Date(m.created_at).toLocaleString()}</span></div><b>${escapeHtml(m.topic)}</b><p>${escapeHtml(m.message)}</p></article>`).join(""); } catch (e) { state.textContent = e.message; if (e.message === "Please log in") { dashboard.hidden = true; loginView.hidden = false; } } }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c])); }
$("login-form").addEventListener("submit", async (e) => { e.preventDefault(); const error = $("login-error"); error.textContent = ""; try { await request("login", { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) }); showDashboard(); } catch (err) { error.textContent = err.message; } });
$("refresh").addEventListener("click", loadMessages); $("logout").addEventListener("click", async () => { await request("logout", { method: "POST" }); dashboard.hidden = true; loginView.hidden = false; });
$("password-form").addEventListener("submit", async (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const state = $("password-state"); if (data.password !== data.confirm) { state.textContent = "Passwords do not match."; return; } try { await request("password", { method: "POST", body: JSON.stringify({ password: data.password }) }); state.textContent = "Password updated."; e.currentTarget.reset(); } catch (err) { state.textContent = err.message; } });
